language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t synthezzz/counter-app

script:
  - docker run -e CI=true synthezzz/counter-app npm run test

deploy:
  provider: elasticbeanstalk
  region: ""
  app: ""
  env: ""
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master
  access_key_id: $
  secret_access_key: $