language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t synthezzz/counter-app -f Dockerfile.dev .

#script:
#  - docker run -e CI=true synthezzz/counter-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "couter3"
  env: "Couter3-env"
  bucket_name: "elasticbeanstalk-us-east-2-720927163681"
  bucket_path: "couter3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY